module.exports = {
  common_create: 'Create',
  common_edit: 'Edit',
  common_modify: 'Modify',
  common_delete: 'Delete',
  common_history: 'History',
  common_project: 'Project',
  common_page: 'Page',
  common_scene: 'Scene',
  common_login: 'Login',
  common_logout: 'Logout',
  common_description: 'Description',
  common_project_manager: 'Project Manager',
  common_project_member: 'Members',
  common_save: 'Save',
  common_submit: 'Submit',
  common_background: 'Background',
  common_bg_image: 'Background Image',
  common_image: 'Image',
  common_success: 'Success',
  common_failed: 'Failed',
  common_search: 'Search',
  common_settings: 'Settings',
  common_create_time: 'Create Time',
  common_last_modifiy_time: 'Last Modify time',
  common_time: 'Time',
  common_creator: 'Creator',
  common_close: 'Close',
  common_confirm: 'Confirm',
  common_preview: 'Preview',
  common_import: 'Import',
  common_export: 'Export',
  common_select: 'Select'
}